---
- name: Install HAProxy and Configure Least Response Time Algorithm
  hosts: load_balancer
  become: yes
  
  tasks:
    - name: Install HAProxy package
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted

# ansible-playbook -i inventory.ini install_haproxy.yml
